default: &default
  adapter: oracle_enhanced
  database: 10.9.7.54:1521/dbdt
  
  username: siatdesv
  password: desenvolvimento

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
