default: &default
  adapter: oracle_enhanced
  username: siatdesv
  password: desenvolvimento
  database: 10.9.7.54:1521/dbdt

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
