default: &default
  adapter: oracle_enhanced
  username: usr_gabrielsantos
  password: e-gov@sefaz

development:
  <<: *default
  database: srvdt.b:1521/dbdt

test:
  <<: *default
  database: srvdt.b:1521/dbdt

production:
  <<: *default
  database: app-oracle1_production
  username: app-oracle1
  password: <%= ENV['APP-ORACLE1_DATABASE_PASSWORD'] %>
